### ISSUE TITLE
Getting the last transaction from a non-existent account via the LiteClient

### ISSUE THREAD

**Issue by jacobs100500** [ton-blockchain/ton#1120]
# Background
I'm trying to get a list of the latest transactions for [this](https://tonviewer.com/UQATlSxDqIUjxatoLCijH_nme_OZZDi_IbiQCpwyJ0S4AMdF) account using LiteClient. This account has a status 'Nonexist', but there are transactions on it.

# Description
To get a list of the latest transactions, you need to send a `liteServer.getTransactions` request, specifying the hash and lt (transaction ID) of the latest transaction on the account in its parameters; otherwise, the response will be an empty list of transactions. To get the latest transaction on the account, I use the `liteServer.getAccountState` or `liteServer.getAccountStatePrunned` request, and from the `liteServer.accountState` response I get the transaction ID. This procedure is taken from the official [documentation](https://docs.ton.org/develop/data-formats/proofs#account-transactions).

The problem is that the `liteServer.accountState` response has an empty account (`account_none$0 = Account`), and the shard state (s`hard_state#9023afe2`) parameter `accounts:^ShardAccounts` is empty. It follows that it is **impossible** to obtain the last transaction ID for such accounts via the LiteClient.

You can only get a list of the latest transactions for this account via the HTTP API. For example, [tonconsole](https://tonapi.io//api-v2#operations-Blockchain-getBlockchainAccountTransactions) does not require specifying the latest transaction to get a list of transactions, but [toncenter](https://toncenter.com/api/v2/#/accounts/get_transactions_getTransactions_get) requires specifying it; otherwise, an empty list will be returned. In addition, both API providers (links to API methods - [tonconsole](https://tonapi.io//api-v2#operations-Blockchain-getBlockchainRawAccount), [toncenter](https://toncenter.com/api/v2/#/accounts/get_address_information_getAddressInformation_get)) have a similar problem as the LiteClient when trying to get the ID of the latest transaction for the account being investigated.

# Enviroments
Any implementation of the LiteClient.
Lite servers from the [global configuration](https://ton.org/global-config.json) are used.

# TL schemas
https://github.com/ton-blockchain/ton/blob/master/tl/generate/scheme/lite_api.tl

**Comment by EmelyanenkoK** [comment]
Liteservers (and nodes generally) store list of transactions on account as singly linked list. Once account is deleted link to prev transaction is removed and tail of the list can not be obtained. This is done for efficiency of node db usage.

However, indexers such as tonapi/toncenter stores data in their own databases that allows them to list all transactions regardless account deletion.

**Comment by DmitryJacobs** [comment]
I'm coding a program that has a function for waiting for operations to complete. It uses only the Lite client to interact with the network.
Transactions on the account above are part of the operations to provide liquidity to DeDast. When I send a message to the network, the program begins to wait for this operation to complete; that is, it waits for the entire chain of transactions for this operation to complete. But this cannot be done for the reason described above.
I can implement this function in other ways:
1) Receive new blocks (`liteServer.listBlockTransactionsExt`) through the Lite client and search for the necessary transactions in them. This option uses significantly more network traffic and computer resources. In addition, public servers have a speed limit (or are overloaded), which entails delays in receiving data.
2) Use a paid subscription tonapi/toncenter, since in the free one you can make 1 request per second (which is extremely little).
3) Use a free subscription tonapi/toncenter and a Lite client in different parts of the program. This method will complicate and confuse the code when theoretically it can be avoided.
4) Install your own Lite server/tonapi/toncenter. I would also like to avoid installing additional and heavy software when, in theory, it is not necessary.

In my opinion, in this case the efficiency of using the database of the Lite server is made to the detriment of its integrity. The Lite server database does not have the last transaction of the account, although in fact it is in the blockchain. It follows from this that the Lite server provides unreliable information, and reliable information can only be obtained through other (paid or difficult to implement) data providers.

I hope you will reconsider your decision and solve this problem with the Lite server/client. Thank you!

**Comment by jacobs100500** [comment]
@EmelyanenkoK 
I'm coding a program that has a function for waiting for operations to complete. It uses only the Lite client to interact with the network.
Transactions on the account above are part of the operations to provide liquidity to DeDast. When I send a message to the network, the program begins to wait for this operation to complete; that is, it waits for the entire chain of transactions for this operation to complete. But this cannot be done for the reason described above.
I can implement this function in other ways:
1) Receive new blocks (`liteServer.listBlockTransactionsExt`) through the Lite client and search for the necessary transactions in them. This option uses significantly more network traffic and computer resources. In addition, public servers have a speed limit (or are overloaded), which entails delays in receiving data.
2) Use a paid subscription tonapi/toncenter, since in the free one you can make 1 request per second (which is extremely little).
3) Use a free subscription tonapi/toncenter and a Lite client in different parts of the program. This method will complicate and confuse the code when theoretically it can be avoided.
4) Install your own Lite server/tonapi/toncenter. I would also like to avoid installing additional and heavy software when, in theory, it is not necessary.

In my opinion, in this case the efficiency of using the database of the Lite server is made to the detriment of its integrity. The Lite server database does not have the last transaction of the account, although in fact it is in the blockchain. It follows from this that the Lite server provides unreliable information, and reliable information can only be obtained through other (paid or difficult to implement) data providers.

I hope you will reconsider your decision and solve this problem with the Lite server/client. Thank you!
