### ISSUE TITLE
Publish statically compiled libemulator artifacts

### ISSUE THREAD

**Issue by dkatzan** [ton-blockchain/ton#1146]
I'm trying to statically compile an executable that includes the libemulator
It will be great if statically compiled version (for mac\linux on arm\x86 arch) can be published as part of the github actions workflow along side the current `.so` and `.dylib` versions

looks like the option already exists in the make system using a `BUILD_SHARED_LIBS` env var https://github.com/ton-blockchain/ton/blob/0c21ce2ee46f5b84c80f0622f79161442642798a/emulator/CMakeLists.txt#L3

**Comment by neodix42** [comment]
Hi,
in every TON [release](https://github.com/ton-blockchain/ton/releases), you can find a bunch of artifacts, among them also statically linked tonlib and emulator.
There are special scripts for building portable versions of binaries, please take a look [here ](https://github.com/ton-blockchain/ton/tree/master/assembly/nix).

**Comment by dkatzan** [comment]
Hi @neodix42 thx for your fast response, I was actually looking at those files and jobs

but it looks like currently for the emulator, only the dynamically build version are uploaded (`libemulator-linux-arm64.so`, `libemulator-linux-x86_64.so`, `libemulator-mac-arm64.dylib`, `libemulator-mac-x86-64.dylib`)
I'm looking for the a statically compiled versions (`.a` files) which aren't seemed to be published currently)

**Comment by neodix42** [comment]
Ah, understood what you mean. You are right, we don't deliver statically linked libraries, only fully portable ones. This is because 
statically linked libraries tend to be more platform-dependent since the entire library code is embedded into the executable, making it tightly coupled to the platform it was compiled for. This results in a need for recompilation if you want to run the executable on a different platform.

**Comment by dkatzan** [comment]
Not sure I follow
there will be 4 more versions based on arch and mac\linux, same as the current dynamically linked versions, no?
 
the context for my ask is I'm having some difficulties in embeding tongo package and using emulator in my project, since we statically compile an executable on linux github runner that is later used inside a docker
 statically compiling fails due to no having such .a file
 trying to dynamically compile works, but fails later at run run time due to some missing symbols:
 
```
 libemulator.so: __vfprintf_chk: symbol not found
libemulator.so: makecontext: symbol not found
libemulator.so: __explicit_bzero_chk: symbol not found
libemulator.so: setcontext: symbol not found
libemulator.so: __sprintf_chk: symbol not found
libemulator.so: getcontext: symbol not found
libemulator.so: __strftime_l: symbol not found
libemulator.so: __vsnprintf_chk: symbol not found
libemulator.so: __memset_chk: symbol not found
libemulator.so: __fdelt_chk: symbol not found
libemulator.so: __fprintf_chk: symbol not found
libemulator.so: __memcpy_chk: symbol not found
```
no sure what's the exact issue, but might be some mismatching glibc issue

so I thought `.a` might help in my use case

**Comment by neodix42** [comment]
Currently, we don't plan to add static versions of tonlib and emulator libraries.
The error you encounter very often happens when you try to compile the project inside Docker Alpine. Even though TON portable binaries are based on musl (which is a minimalistic of glibc), on Alpine you need to install glibc.
In short, it's not a problem of TON shared libraries, but rather with your environment. In case you have further problems, please share your env details and steps to reproduce the issue.
