### ISSUE TITLE
What FileSystem do you suggest to use?

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#124]
What FS should I use to run Full Node/Validator? I guess the options are ext4 or XFS? What do you suggest based on your experience?

**Comment by ton-blockchain** [comment]
Use XFS if possible. Ext4 would be less efficient, at least for the testnet and for the mainnet when most blocks are underloaded and short, because each block is kept in a separate file, and Ext4 is not very efficient in handling a lot of small files. With Ext4, you might run out of inodes even with the partition only half full.

**Comment by akme** [comment]
Thanks!
