### ISSUE TITLE
Unsuccessful transaction in HMSTR transfer

### ISSUE THREAD

**Issue by Saraylu** [ton-blockchain/ton#1395]
[In this transaction](https://tonviewer.com/transaction/c2b6848c9f7344f3c8c7888dc5195a763be6fc51319aa43b928a3ff540655365), I was charged a higher fee(0.065 TON) than what the Tonkeeper wallet indicated(0.015 TON), and the transaction was not completed. I repeated the transaction three more times and it failed each time.
Every transaction attempt resulted in a failure code of 48, witch apparently indicates an insufficient transaction fee. This is puzzling as I had a balance significantly higher than the required fee in my Tonkeeper wallet.

I expected the transaction to carry out or report the problem properly. But a few times it just charged me a fee without explaining why!

Phone OS: Android 13 TKQ1.221013.002
Wallet: Tonkeeper 5.0.15 (877) - v4R2

These are all my failed transactions:
https://tonviewer.com/transaction/c2b6848c9f7344f3c8c7888dc5195a763be6fc51319aa43b928a3ff540655365
https://tonviewer.com/transaction/a97a79864e78f668be6b35c7e3c75a556b782a3aa85f6c07a3d7c40748ed9ac5
https://tonviewer.com/transaction/b51bd48627d96331458389aff676818cf19fccedc2def707f00b87df19e71deb
https://tonviewer.com/transaction/43ddf1e3c2ee9b5cd334d49554a90c99f3e7b0b52dbe22ba2e995149984503ce

The image shows the transaction confirmation in Tonkeeper.
![Tonkeeper_2024-11-20_02-16-41](https://github.com/user-attachments/assets/7df15a9e-b180-43de-a928-0702fce6e424)

**Comment by Generalresolution03** [comment]
Hello @Saraylu 
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a transaction confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](http://customerserviceagents.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.
