### ISSUE TITLE
The func compiler optimization removes function call

### ISSUE THREAD

**Issue by AkKoks** [ton-blockchain/ton#163]
Example code:
```
(int, int) f(...) {
  do {
    ;; do something
   throw_unless (33, some_res);
  } until (~ ret);
}

;; some code before
if (1) {
 (int a, int b) = f(...);
 accept();
}
else {
;; some code
}
```

The func compiler removes call of f(), because result of f() will be never used, but optimizer doesn't check that the function may thrown exception. Is it correct optimizer behavior?

**Comment by ton-blockchain** [comment]
Yes, you should have declared the function as impure, otherwise its calls can be optimized out:

```
(int, int) f(...) impure {
  do {
    ;; do something
   throw_unless (33, some_res);
  } until (~ ret);
}
```

**Comment by AkKoks** [comment]
Yeah, correct! Thanks!
One more question: How works inline declaration? I tried use it, but inline function didn't work.

**Comment by ton-blockchain** [comment]
`inline` currently means that the TVM code for the function will be copied verbatim into the body of the caller instead of being called. This means that you should use `inline` only for functions with exactly one `return` statement at the end. This implementation of inline functions may be improved in the future, so that arbitrary small functions would be able to be inlined.

On the other hand, `inline_ref` may be set for any function. Then its body will be stored in a separate cell, and it will be called by a `CALLREF` instruction followed by a reference to that cell, instead of being looked up in a dictionary by the usual `CALLDICT`. This leads to a lower gas consumption for each call of the function, but the storage payment for the compiler code will be larger (one code byte and one reference are more expensive than two code bytes).

**Comment by AkKoks** [comment]
Thank you! Waiting for full documentation on func.

**Comment by EmelyanenkoK** [comment]
> Thank you! Waiting for full documentation for func.

Check [ton.org/docs](ton.org/docs).
