### ISSUE TITLE
Example of server.list config for generate-test-node-config.py

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#194]
Could you please provide an example of "server.list" config for test/generate-test-node-config.py?

**Comment by ton-blockchain** [comment]
You do not need this (undocumented) script unless you want to start a totally independent instance of the whole TON Network (not just of TON Blockchain). You'll need at least 100 nodes for bootstrapping a separate instance of TON Network. It does not seem likely that you really want this unless you want to test a drastically uncompatible upgrade of TON Network protocols, because the existing only instance of TON Network can accomodate as many test instances of TON Blockchain as required.
