### ISSUE TITLE
Please add dict! , dict@ methods to Fift

### ISSUE THREAD

**Issue by tolya-yanot** [ton-blockchain/ton#221]
Currently Fift has methods for working with dictionaries with int and uint keys: idict!, idict@, udict!, udict@, ... etc.

Please add methods for working with dictionaries with slice keys: dict!, dict!+, b>dict!, b>dict!+, dict@

TVM supports such dictionaries (DICTGET, DICTSET), but now we do not have the ability to prepare data in Fift scripts

**Comment by Skydev0h** [comment]
It may be not that easy to name because dict@ is already occupied for fetching dictionary itself.

On the other hand, at least for upto 256-bit slices it is very simple to emulate those functions with fift:
```
{ rot over u@ -rot   udict!  } :   sdict!
{ rot over u@ -rot   udict!+ } :   sdict!+
{ rot over u@ -rot b>udict!  } : b>sdict!
{ rot over u@ -rot b>udict!+ } : b>sdict!+
{ rot over u@ -rot   udict@  } :   sdict@
```

It may be reasonable to call those functions sdict because slices are keys.

Implementing this is actually easy, [for example like this](https://github.com/Skydev0h/ton/commit/22f32e13bef22be6ffc94f9dd481a0ca7df62790), that branch is referenced in PR #220.

**Comment by Skydev0h** [comment]
@tolya-yanot It seems that the methods [were added with the last commit](https://github.com/ton-blockchain/ton/commit/acf16718e6385685828316ec116f12cb60455047#diff-96b137d7cd846d88ed7648d46c52b8b9R2748).

**Comment by ton-blockchain** [comment]
Yes, the requested words should be now available in the latest version of Fift. Please check.
