### ISSUE TITLE
Possible small bug in elector-code + some trivial notices

### ISSUE THREAD

**Issue by Skydev0h** [ton-blockchain/ton#225]
I analyzed core FunC contracts and found a possible bug and some places seeking more attention:

**elector-code.fc**
```
W 608 fs~load_uint(32) result unfreeze_time is unused and is unconditionally 
      overwritten with now() + stake_held, possible logic error, revising recommended

I 181 weight unused, suggesting replacement with _
I 201 weight unused, suggesting replacement with _
I 223 data1, vset_hash, complaints unused, suggesting replacement with _
I 807 time unused, suggesting replacement with _
```

**config-code.fc**
`I 181 entry initial value null() is not used in any execution path`

**restricted-wallet-code.fc**
`I 20 s_addr unused, suggesting replacement with _`

Most of those are trivial "replace with hole _" notices, except for warning about elector-code.fc:608, which should be looked into and is the reason for this issue.

Looks like a leftabout from old version of code that added stake_held to unfreeze_time, maybe?

_P.S.: Nice to say that all other core contracts did not trigger any warnings... yet._

**Comment by ton-blockchain** [comment]
Thank you for this feedback. However, the code near the first warning (the most suspicious indeed) is in fact correct (we want to deserialize the value of a field from a TL-B structure and overwrite this value completely). The other places (with unused variables) are better kept with the explicit variable names, which take place of field names in a structure. In particular, this simplifies bug detection if a structure is incorrectly (de)serialized, and the code for (de)serializing the same structure can be copied into several places even if some fields are unused on each occasion.

As to the warning in `config-code.fc`, it is due to the fact that there are no uninitialized local variables in FunC (because some value has to be pushed into the TVM stack to represent a new local variable), and `var entry` could not be declared inside `if` and `else` branches (because it has to be used after the `if` statement). A possible alternative solution would be to allow uninitialized local variables if they are initialized in different if-else branches (or loop bodies) before being used, but implementing this correctly would be quite complicated.

**Comment by Skydev0h** [comment]
Useful explanation, indeed, that is logical and optimal despite that code may look like a possible mistake without such understanding. Copying (de)serialization code a bit breaks the DRY principle, that way, if a structure needs to be changed, it can become quite complicated. However as I see it is not possible to counter that without introducing some complicated features to the compiler (such as macros or structures or something like that).

Technically the fact that instruction is optimized out is the reason for the warning, it outlines possible logic errors and actually yet cant catch mistakes that for some reason were not optimized out.

_I hope that in some time we would have fully functional static analyzer for the FunC that would smartly analyze logic code flows and think better on them._

</issue>
