### ISSUE TITLE
Prohibitive dictionary lookup fee

### ISSUE THREAD

**Issue by EmelyanenkoK** [ton-blockchain/ton#234]
Ability to interact with blockchain entities from outside, that is external messaging, is a killer feature of TON blockchain.
However spectrum of applications which can utilize this feature is severely limited by relation between `gas_credit` and fees for `*DICTGET*` methods. More details can be found here: https://t.me/ton_overview/35

Please, consider radical discount for non-changing dictionary lookups.

**Comment by koinov** [comment]
The case, described in the link above is really worth to implement. Tokens are basic feature used by almost every blockchain projects. This or any other way, allowing implementation of basic token functionality, operated by external transactions, can significantly increase interest in TON for developers.

**Comment by ton-blockchain** [comment]
The dictionary operations do not have a large gas price by themselves. Instead, cell dereference fees (100 gas units) and cell creation fees (500 gas units) are accumulated as appropriate during the tree traversal performed by a dictionary operation. We do not think that dictionary operations should get a discount when invoking these basic cell access operations, otherwise somebody would simply use them to make all cell accesses cheaper by performing them as specially crafted dictionary accesses.

On the other hand, we do not think that the 100 gas units price for dereferencing a cell (a "cell load" operation) could be lowered much further, because this operation may involve loading a data cell (belonging to the code or data of a large smart contract) from the persistent disk storage, which is a slow operation that should not be encouraged.

What can be done is decreasing the price of subsequent accesses to the same cell inside one run of the TON VM. For instance, we could modify TON VM to collect 100 gas units only for the first access to a cell, and collect only 25 gas units for all subsequent accesses. We are not sure whether this would be useful for the specific purpose mentioned in the link.

**Comment by EmelyanenkoK** [comment]
>We do not think that dictionary operations should get a discount when invoking these basic cell access operations, otherwise somebody would simply use them to make all cell accesses cheaper by performing them as specially crafted dictionary accesses.

Probably, if dictionary operations would have discount not on each inner step, but for all steps at once as for batch operations, it will solve the issue of exploiting DICT-operations as cheap dereferences. I'm talking, for instance, about the scheme, where for each subsequent cell dereference operations during one dictionary lookup fee will be twice as lower.

Another possible way of getting the same result, which may be more aligned with inner logic of TON VM is new operations for navigated dictionary lookup. For many cases user which triggers contract may execute dictionary lookup locally, and then pass the result cell index (assuming that contract data-cell is indexed) to the contract. Of course contract should make some checks that user provided correct index (nasty, but straight-forward approach will be key-duplication in the leaf). 
The idea here is that as much work as possible should be make outside of the VM, thus if something can be found locally and then just checked in VM it should be done this way, instead of searching in VM (and thus repeating the same work on all validators nodes).
