### ISSUE TITLE
Wrong "now" value in transaction raw data

### ISSUE THREAD

**Issue by logvik** [ton-blockchain/ton#47]
For example, if check the testgiver account that we will see the value for now:1569426502 always the same.
https://test.ton.org/testnet/transaction?account=Ef_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYDJ4&lt=223985000005&hash=2F9644B4AE4FE4155632E2ED8E48F3DE8ED0CBEC0A237CD022BFB8797A79F9CF
https://test.ton.org/testnet/transaction?account=Ef_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYDJ4&lt=223985000002&hash=1727F05C2489762729AAE35970A4CD56DF9D6E1C39F68D730B5AAAD4177195B0

For all transactions, the value for "now" is 1569426502. it is "now" for the last transaction.

**Additional note**: Only hash and lt are changing. Raw data is the same for all transactions.

**Comment by ton-blockchain** [comment]
No, it isn't. The two transactions you indicate are in the same block, that's why they have the same unixtime (equal to the creation time of that block). However, even the inbound external messages of the two transactions are different in their value fields. The transactions themselves are also different.

If you inspect other transactions of the same account contained in different blocks, you'll see they have different creation times:

https://test.ton.org/testnet/transaction?account=Ef_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYDJ4&lt=223983000011&hash=31B1448251318A6D87B789E8BDABEF97CA05A4E65F976FF6D8C2FD8551027241
