### ISSUE TITLE
TON DNS - Resolve name and nslookup utility

### ISSUE THREAD

**Issue by air3ijai** [ton-blockchain/ton#676]
How we can resolve TON DNS name in a simple way?

1. [TON DNS & Domains](https://docs.ton.org/participate/web3/dns)
2. [What is TON DNS?](https://docs.ton.org/learn/services/dns)
3. [TEPs/text/0081-dns-standard.md](https://github.com/ton-blockchain/TEPs/tree/master/text/0081-dns-standard.md)

Questions
1. Can we do it somehow via TON Explorer and which one?
2. Can we do it somehow via CLI app?

Thanks!

**Comment by air3ijai** [comment]
Now, we are trying to follow the guide [Accessing TON Sites](https://docs.ton.org/participate/web3/sites-and-proxy#accessing-ton-sites), it does not work as it was already mentioned in the [Access TON Site on TON Storage via TON Proxy #677](677).

In the guide, you propose to access the site `just-for-test.ton` using two addresses via TON Proxy
1. http://just-for-test.ton
2. http://utoljjye6y4ixazesjofidlkrhyiakiwrmes3m5hthlc6ie2h72gllt.adnl

How we can get ADNL address from the TON DNS one?

**Comment by justdmitry** [comment]
> How we can get ADNL address from the TON DNS one?

ADNL address is stored in "site" record in DNS NFT contract data, see https://github.com/ton-blockchain/TEPs/blob/master/text/0081-dns-standard.md#dns-records

Once you spin-up some server to host your site - you should put adnl address of this server to 'site' record of your domain via dns.ton.org (or programmatically). And proxy will read this record and request specified server for your site files.

**Comment by air3ijai** [comment]
> ADNL address is stored in "site" record in DNS NFT contract data, see https://github.com/ton-blockchain/TEPs/blob/master/text/0081-dns-standard.md#dns-records

Sounds clear, but how we can do it via Explorer?

For example, `just-for-test.ton` is owned by the [EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N](https://tonscan.org/address/EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N) address.

1. How can we find address of the resolver?
   - This one - [.ton DNS](https://tonscan.org/address/EQC3dNlesgVD8YbAazcauIrXBPfiVhMMr5YYk2in0Mtsz0Bz)?
   - Is it a [Root DNS](https://github.com/ton-blockchain/TEPs/blob/master/text/0081-dns-standard.md#root-dns)?
2. How can we call resolver to get the value stored in the `site` record? Is there any examples how can we do that using curl or maybe there is a native CLI app for that?

> Once you spin-up some server to host your site - you should put adnl address of this server to 'site' record of your domain via dns.ton.org (or programmatically).

I'm discovering a way to do it via TON Storage, rather than TON Proxy. It is much easier to run 10 TON Storage nodes which will download and redistribute specific BagID, than to run TON Proxy and take care about distributing same private key to all nodes.

> And proxy will read this record and request specified server for your site files.

It means that proxy can resolve the address?

**Comment by justdmitry** [comment]
> Sounds clear, but how we can do it via Explorer?

I don't know if any explorer can show you this (this info is public, but no one can list all stored DNS "records" AFAIK). To update - only domain owner can do it via dns.ton.org or sending special message to dns nft.

-----

> For example, just-for-test.ton is owned by the `EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N` address.

Do not be confused with "NFT owner". For example "foundation.ton" domain (I don't want to spend time repeating for just-for-test one, sorry) has this addresses:

 * DNS NFT item itself is [EQB43-VCmf17O7YMd51fAvOjcMkCw46N_3JMCoegH_ZDo40e](https://tonscan.org/address/EQB43-VCmf17O7YMd51fAvOjcMkCw46N_3JMCoegH_ZDo40e)
 * Owner of this item is [EQCdqXGvONLwOr3zCNX5FjapflorB6ZsOdcdfLrjsDLt3Fy9](https://tonscan.org/address/EQCdqXGvONLwOr3zCNX5FjapflorB6ZsOdcdfLrjsDLt3Fy9) - person who has this NFT in his "NFT list" in explorers
 * Assigned "wallet" (DNS entry in DNS NFT item data) is [EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N](https://tonscan.org/address/EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N) - but it doesn't have "foundation.ton" NFT in his "NFT list" in explorer.

So "owner" opened dns.ton.org and put "assigned" address in "wallet" record. It's like in real life, say, Everscale devs purchase "the-best-crypto.org" domain and make it redirect to "ton.org".

For now explorers (e.g. tonscan.org) will redirect you to "assigned" wallet EQCD...qB2N when you search for "foundation.ton", not to NFT one. I have created https://github.com/catchain/tonscan/issues/63 issue for them to show both.

I don't know if other explorer can show you more info, instead I used [this C# code](https://github.com/justdmitry/TonLib.NET/blob/master/TonLibDotNet.Demo/Samples/ResolveDomains.cs).

-----

> I'm discovering a way to do it via TON Storage

To server side from TON Storage, you need to put storage bag-id into "site" record of DNS NFT Item (instead of server ADNL) on dns.ton.org. The proxy is responsible for connecting to storage bag instead of adnl server.

**Comment by justdmitry** [comment]
> How we can resolve TON DNS name in a simple way?

I created Telegram bot https://t.me/TonDomainInfoBot that shows detailed info from DNS-enabled smartcontracts. It currently supports *.ton domains, *.t.me usernames and +888 anonymous numbers.

**Comment by air3ijai** [comment]
Found other ways in [TON DNS documentation](https://ton-telegram.network/ton-dns-documentation/)

#### lite-client

 1. Download `lite-client` - https://github.com/ton-blockchain/ton/releases
 2. Download `global.config.json` - https://github.com/ton-blockchain/ton-blockchain.github.io
 3. Run a query
    ```shell
    lite-client -C global.config.json -c "dnsresolve just-for-test.ton"
    ```
    ```shell
    Result for domain 'just-for-test.ton' (all categories)
    raw data: x{77}
    x{BF235101421CF6EA196A9F05C2AD3339936420E68D373F5B3DC74538081510EC6E_}
      x{9FD380107BFAAA5CC6E5368E5F9799188BD798CD22E04AB16D1D8EA4FC37480741E635001_}
    x{BF2EB8106C0B107B43F6293BEC0E6F1E0375ABD287C31083D09586B9C177690FFA_}
      x{747356A168B40A04E646DB7717B9E2CDAC79F904E5D0F7CDB2419FE8F8F7160C6FE7}

    category 6NRAUIc9uoZap8Fwq0zOZNkIOaNNz9bPcdFOAgVEOxs= : (dns_smc_address
      smc_addr:(addr_std
        anycast:nothing workchain_id:0 address:x83DFD552E63729B472FCBCC8C45EBCC6691702558B68EC7527E1BA403A0F31A8) flags:0)
      smart contract 0:83DFD552E63729B472FCBCC8C45EBCC6691702558B68EC7527E1BA403A0F31A8 = EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N
    category +64EGwLEHtD9ik77A5vHgN1q9KHwxCD0JWGucF3aQ/4= : (dns_storage_address bag_id:x56A168B40A04E646DB7717B9E2CDAC79F904E5D0F7CDB2419FE8F8F7160C6FE7)	storage address 56A168B40A04E646DB7717B9E2CDAC79F904E5D0F7CDB2419FE8F8F7160C6FE7
    arguments:  [ CS{Cell{000200} bits: 0..8; refs: 0..0} 0 123660 ]
    result:  [ 8 C{BF380AD719E6CC14935EF87C720C5D585ABADF208BC16FD444DEC96AEF43D722} ]
    remote result (not to be trusted):  [ 8 C{BF380AD719E6CC14935EF87C720C5D585ABADF208BC16FD444DEC96AEF43D722} ]
    ```

**Comment by air3ijai** [comment]
#### tonlib-cli

 1. Download `tonlib-cli` - https://github.com/ton-blockchain/ton/releases
 2. Download `global.config.json` - https://github.com/ton-blockchain/ton-blockchain.github.io
 3. Run a query
    ```shell
    tonlib-cli -c global.config.json -E "dns resolve root just-for-test.ton"
    ```
    ```shell
    synchronization: ???
    synchronization: 0%
    synchronization: DONE in 166.3ms
    synchronization: 100%
    synchronization: DONE in 60.8ms
    Done
      6NRAUIc9uoZap8Fwq0zOZNkIOaNNz9bPcdFOAgVEOxs= SMC:EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N
      +64EGwLEHtD9ik77A5vHgN1q9KHwxCD0JWGucF3aQ/4= STORAGE:56A168B40A04E646DB7717B9E2CDAC79F904E5D0F7CDB2419FE8F8F7160C6FE7
    ```
