### ISSUE TITLE
Function selector

### ISSUE THREAD

**Issue by KStasi** [ton-blockchain/ton#92]
Is any way to specify a function selector for internal msg or get the state of one smart contract from another one using func?

**Comment by ton-blockchain** [comment]
1. We don't quite understand this question, but if you wanted to ask if an internal message may be automatically processed by the destination smart contract with a non-zero method selector, the answer is NO. On the other hand, the recommended layout of internal messages includes an "operation selector" in the first 32 bits of the message body, which can be used by the receiver to select and run the appropriate function (from `recv_internal`).

2. No, you cannot directly inspect the state of one smart contract from another, because they reside in different shardchains and cannot see the state of each other. All interaction between smart contracts is by message passing ("Actor model"), so if smart contract A wants to learn something about the state of smart contract B, it has to send a message to B with an appropriate query, and B has to support that query and send a response with the relevant information from the state of B.
